### ISSUE TITLE
Some question about Regularized Newton Raphson Inversion for  Text-to-Image Diffusion Models

### ISSUE THREAD

**Issue by Ed-ivan** [dvirsamuel/FPI#1]
A great and interesting work and thanks for sharing your code , while I have some questions about <<Regularized Newton Raphson Inversion for Text-to-Image Diffusion Models>> ,  I can not find the code releated  Regularized Newton Raphson , can you help me ? 

Looking forward to your reply.

**Comment by wentaohu1208** [comment]
same question

**Comment by dvirsamuel** [comment]
Hey, 
Thank you for your interest in our work.
We are planning to release demo and code very very soon. 
I'll update you here when the code is online.

Dvir

**Comment by suhas1999** [comment]
Hey Dvir,

Thanks for the amazing work , by when can we expect the code ?

**Comment by dvirsamuel** [comment]
Hey,
We have published hf demo: https://barakmam.github.io/rnri.github.io/
Currently, the code can be found in the hf repo. We are planning to release more code and resources on github soon.
